Feature: Item grouping
rune-js/server pull request #361
Opened 2021-12-27 15:47 UTC by Promises

Add a new function to deepmerge objects (this should be checked by somebody, might have issues, though i hope not)

some groups added to adamant-armour.json, black-armour.json, bronze-armour.json, bronze-weapons.json.

new command to quickly test groups, usage:
selectgroups groupA,groupB (comma seperated list of groupnames, will return all items in all groups)
filtergroups groupA,groupB (comma seperated list of groupnames, will return only items which are shared between groups)

2021-12-27 15:50 UTC, Promises commented
![image](https://user-images.githubusercontent.com/4681207/147487358-4fab3c1d-3e95-4d46-a3e2-9f9086c81e96.png)

2022-01-03 15:30 UTC, SchauweM requested changes
I like what you've done.  I don't know if there is another way to handle this tho so I'm curious what the other contributors think of your solution.

2022-01-03 15:30 UTC, SchauweM commented on src/engine/config/config-handler.ts
> +export const findItemTagsInGroup = (groupKey: string | string[]): string[] => {
I'd use the plural version just so it's clear we're talking about an array of multiple entries. Same goes for all the rest in this file

2022-01-03 17:38 UTC, Kikorono requested changes
Only some small lint-related things, looks awesome!!

2022-01-03 17:38 UTC, Kikorono commented on src/engine/config/config-handler.ts
> +        const collection: Record<string, boolean> = {}
Missing a few semi-colons in this'n

2022-01-03 17:38 UTC, Kikorono commented on src/engine/config/config-handler.ts
> +    let collection: Record<string, boolean> | undefined = undefined
Some more semi-colons

2022-01-03 17:38 UTC, Kikorono commented on src/engine/util/objects.ts
> +export function deepMerge<T>(objectA: T, objectB: T): T {
Good candidate for the `common` library in the future :)

2022-11-23 19:14 UTC, Kikorono approved these changes

2022-11-25 20:56 UTC, SchauweM approved these changes

2022-11-25 20:56 UTC, merged