refactor: delete old combat code
rune-js/server pull request #378
Opened 2022-09-16 12:20 UTC by Jameskmonger

The existing combat code had a few issues:
- the ticks were not synchronised between entities so hits weren't timed correctly
- tailing also wasn't synchronised between entities so the pathfinding would often put combatants in the wrong place
- the code was almost entirely within the Actor/NPC/Player classes

As we are going to be rewriting combat in the upcoming Task system, this PR removes the old code - we can use this PR as a reference when reimplementing it.

This PR also removes the `Behaviour` system as it was only used for combat and can be replaced with Tasks.

2022-09-16 12:30 UTC, SchauweM requested changes
You've missed some things
- `player.ts:780` - Prayers and other effects affect strength bonuses 

Do we want to keep those or remove them from `updateBonuses()`?

2022-09-16 12:52 UTC, Jameskmonger commented
@SchauweM changes addressed!

2022-09-17 18:35 UTC, Kikorono approved these changes

2022-09-19 11:57 UTC, SchauweM approved these changes

2022-09-19 11:59 UTC, merged